#####################################################################################
# dwca_term_values.yaml
#####################################################################################
#
# This workflow:
#    - creates a given directory as a workspace
#    - downloads a Darwin Core Archive from a given URL
#    - extracts the core file of a Darwin Core Archive to a tab-separated text file
#    - for each field in a given list of fields, creates a report of counts of distinct 
#      values
#    - wraps up the workflow
#
# Example command-line usage:
# kurator -f dwca_term_values.yaml 
#         -p workspace=./dwca_term_values_workspace
#         -p dwca_url=http://ipt.vertnet.org:8080/ipt/archive.do?r=ccber_mammals
#         -p format=txt
#         -p fieldlist="genus|specificepithet"
#         -l DEBUG (optional)
#
# Requires:
# jython pip install requests
# jython pip install python-dwca-reader
# jython pip install py
# jython pip install unicodecsv
# jython pip install unidecode
#
#####################################################################################
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# __author__ = "John Wieczorek"
# __copyright__ = "Copyright 2016 President and Fellows of Harvard College"
# __version__ = "dwca_term_values.yaml 2016-10-13T00:13+02:00"

imports:

- classpath:/org/kurator/akka/types.yaml

# Definitions of the Workflow and actors
components:

### The named workflow ###
- id: DwCATermCounter
  type: Workflow
  properties:
    actors:
      # Actors invoked in the workflow. Every actor that will be invoked must be on this
      # list. Though the order does not matter, it is helpful to keep the list in more
      # or less the order in which they'll be invoked, for clarity.
      - !ref MakeWorkspace
      - !ref DownloadArchive
      - !ref ExtractArchiveCore
      - !ref CountFieldValues
      - !ref WrapUp
    # Each parameter defined here enters the workflow from the command line and is 
    # delivered in the options dictionary of the specified actor.
    parameters:
      # Accept a parameter called dwca_url from the command line.
      dwca_url:
        # Set the url in the options dictionary of DownloadArchive from the value
        # of the dwca_url parameter given on the command line.
        actor: !ref DownloadArchive
        parameter: url
      # Accept a parameter called workspace from the command line.
      workspace:
        # Set the workspace in the options dictionary of MakeWorkspace from the value
        # of the workspace parameter given on the command line.
        actor: !ref MakeWorkspace
        parameter: workspace
      # Accept a parameter called format from the command line.
      format:
        # Set the format in the options dictionary of CountFieldValues from the value
        # of the format parameter given on the command line.
        actor: !ref CountFieldValues
        parameter: format
      # Accept a parameter called fieldlist from the command line.
      fieldlist:
        # Set the fieldlist in the options dictionary of CountFieldValues from the value
        # of the format parameter given on the command line.
        # Example: 'country|state|county|year'
        actor: !ref CountFieldValues
        parameter: fieldlist

# Inline python actor to make a workspace on the fly to use for writing temporary 
# if one is not supplied in the workflow-defined parameters. It creates a unique
# workspace if a workspace location is not explicitly provided, or if the provided
# one does not exist.
- id: MakeWorkspace
  type: NativePythonActor
  properties:
    onStart: on_start
    # Inline python code to run.
    code: |
        import uuid
        import os
        # The function to run when an on_start message is received. Accepts a dictionary
        # of options.
        def on_start(options):
            actor = 'MakeWorkspace'
            print '### Started %s ###' % actor
            for key, value in options.iteritems():
                print '%s: %s' % (key, value)
            options['success']=True
            if options.has_key('workspace') == False:
                options['workspace'] ='./workspace_'+str(uuid.uuid1())
            if not os.path.exists(options['workspace']):
                os.makedirs(options['workspace'])
            if not os.path.exists(options['workspace']):
                options['success']=False
                options['message']='Unable to create workspace at %s' % options[workspace]
            else:
                options['message']='Created workspace %s' % options['workspace']
            return options

# Download a Darwin Core archive from a URL given by workflow-defined url parameter. 
# Download occurs in workspace provided by the upstream actor.
- id: DownloadArchive
  type: NativePythonActor
  properties:
    # The location of the actor source code
    module: kurator_dwca.downloader
    # The function to invoke in the module when the actor receives an onData message.
    onData: downloader
    # A list of parameters to get from the options dictionary passed from an 
    # upstream actor.
    inputs:
      # Get the workspace for this actor from the workspace in the options dictionary.
      workspace : workspace
    # A list of parameters to get from the parameters defined at the workflow level or
    # to set explicitly from values given in this section.
    parameters:
      # Get the url for the options dictionary from the url parameter defined 
      # in the Workflow. It is not declared here.
      # NOTE: Would like to establish the command line source of a parameter here, within
      # the actor.

      # Set the outputfile to a specific file name.
      # Download to a specific file name within the workspace.
      outputfile: 'dwca.zip'
      # Invoking python logging causes thread exceptions.
    # The "upstream" actor from which to receive a message.
    listensTo:
      - !ref MakeWorkspace

# Extract core file into a tab-separated value file in workspace from Darwin Core archive.
- id: ExtractArchiveCore
  type: NativePythonActor
  properties:
    # The location of the actor source code 
    module: kurator_dwca.dwca_core_to_tsv
    # The function to invoke in the module when the actor receives an onData message.
    onData: dwca_core_to_tsv
    # A list of parameters to get from the options dictionary passed from an 
    # upstream actor.
    inputs:
      # Get the inputfile for this actor from the outputfile in the options dictionary.
      outputfile: inputfile
      # Get the workspace for this actor from the workspace in the options dictionary.
      workspace : workspace
    # A list of parameters to get from the parameters defined at the workflow level or
    # to set explicitly from values given in this section.
    parameters:
      # Set the outputfile to a specific file name within the workspace.
      outputfile: 'dwca_extracted_occurrences.txt'
    # The "upstream" actor from which to receive a message.
    listensTo:
      - !ref DownloadArchive

# Inline python actor to create distinct value counts all DwC terms recommended to follow
# controlled vocabularies.
- id: CountFieldValues
  type: NativePythonActor
  properties:
    onData: on_data
    # Inline python code to run.
    code: |
        # The function to run when an on_data message is received. Accepts a dictionary
        # of options.
        from kurator_dwca.dwca_utils import read_header
        from kurator_dwca.dwca_utils import clean_header
        from kurator_dwca.dwca_utils import csv_file_encoding
        from kurator_dwca.dwca_terms import controlledtermlist
        from kurator_dwca.term_value_count_reporter import term_value_count_reporter
        def on_data(options):
            actor = 'CountFieldValues'
            print '### Started %s ###' % actor
            for key, value in options.iteritems():
                print '%s: %s' % (key, value)

            # Get the format for the output files, with 'csv' as the default
            try:
                format = options['format']
            except:
                format = 'csv'

            # Figure out the input file encoding first. It will makes things much faster
            # to know it in advance and pass that information to various steps.
            #encoding = csv_file_encoding(options['inputfile'])
            encoding = 'utf-8'
            header = read_header(options['inputfile'], encoding=encoding)

            # Create a cleaned list of fields from the input file
            cleanheader = clean_header(header)

            # Turn the input fieldlist into a cleaned list
            try:
                fieldlist = options['fieldlist']
            except:
                fieldlist = 'country'
            termsofinterest = fieldlist.split('|')
            cleantermlist = clean_header(termsofinterest)

            # Get a list of fields from those of interest that actually exist in the 
            # inputfile
            termlist = []
            for term in cleantermlist:
                if term in cleanheader:
                    termlist.append(term)

            # Prepare the output dictionary
            outputoptions = {}
            outputoptions['success'] = True
            outputoptions['message'] = None
            outputoptions['workspace'] = options['workspace']
            outputoptions['artifacts'] = {}

            # Cycle through all of the fields of interest in the inputfile
            for term in termlist:
                filename = 'count_'+term.lower()+'.'+format

                # Prepare the options dictionary for the term_value_count_reporter
                counteroptions = {}
                counteroptions['workspace'] = options['workspace'] 
                counteroptions['inputfile'] = options['inputfile']
                counteroptions['outputfile'] = filename
                counteroptions['format'] = format
                counteroptions['termlist'] = [term]
                counteroptions['encoding'] = encoding

                # Create the reports
                results = term_value_count_reporter(counteroptions)
                if results['success'] == False:
                    outputoptions['success'] = False
                    outputoptions['message'] = results['message']
                    return outputoptions
                else:
                    artifact_key = '%s_count_file' % term
                    outputoptions['artifacts'][artifact_key] = results['outputfile']
            return outputoptions
    # A list of parameters to get from the options dictionary passed from an 
    # upstream actor.
    inputs:
      # Get the inputfile for this actor from the outputfile in the options dictionary.
      outputfile: inputfile
      # Get the workspace for this actor from the workspace in the options dictionary.
      workspace : workspace
      # Get the success state from the options dictionary of the previous step
      success: previoussuccess
      # Get the message from the options dictionary of the previous step
      message: previousmessage
    # The "upstream" actor from which to receive a message.
    listensTo:
      - !ref ExtractArchiveCore

# Inline python actor to take care of any unfinished business and finish the workflow.
- id: WrapUp
  type: NativePythonActor
  properties:
    onData: on_data
    # Inline python code to run.
    code: |
        # The function to run when an on_data message is received. Accepts a dictionary
        # of options.
        def on_data(options):
            actor = 'WrapUp'
            print '### Started %s ###' % actor
            for key, value in options.iteritems():
                if key == 'artifacts':
                    print 'artifacts:'
                    keylist = []
                    for akey, avalue in options[key].iteritems():
                        keylist.append(akey)
                    sortedkeylist = sorted(keylist)
                    for skey in sortedkeylist:
                        print '  %s: %s' % (skey, options[key][skey])
                else:
                    print '%s: %s' % (key, value)
            print '### Finished Wrapup ###'
    # A list of parameters to get from the options dictionary passed from an 
    # upstream actor.
    inputs:
        # Get the workspace for this actor from the workspace in the options dictionary.
        workspace: workspace
        # Get the success state from the options dictionary of the previous step
        success: previoussuccess
        # Get the message from the options dictionary of the previous step
        message: previousmessage
    parameters:
      # Show the name of the upstream actor.
      messagefrom: 'CountFieldValues'
    # The "upstream" actor from which to receive a message.
    listensTo:
      - !ref CountFieldValues
